# Number of days of inactivity before an issue becomes stale.
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed.
daysUntilClose: false

# Issues with these labels will never be considered stale.
exemptLabels:
  - type: "Type: Bug"
  - type: "Type: Security"

# Set to true to ignore issues in a milestone (defaults to false).
exemptMilestones: false

# Label to use when marking an issue as stale.
staleLabel: "Type: Stale"

# Comment to post when marking an issue as stale. Set to `false` to disable.
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. If this issue is still relevant then let us know how to help move it forward.
  Thank you for your contributions.

# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false

# Comment to post when closing a stale Issue or Pull Request. Set to `false` to disable
closeComment: false