---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/base-ci
    tag: kubecf
inputs:
- name: ci
- name: s3.stemcell-version
- name: kubecf
- name: built_images
params:
  STEMCELL_VERSIONED_FILE: ~
  GITHUB_TOKEN: ~
  GIT_MAIL: ~
  GIT_USER: ~
  RELEASE_NAME: ~
  BUILDPACK_NAME: ~
  KUBECF_BRANCH: ~
  KUBECF_VALUES: ~
  BUILT_IMAGES: ~
run:
  path: ci/.concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
