---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: splatform/catapult
inputs:
- name: kubecf
- name: kind-environments
- name: catapult
- name: s3.kubecf-ci
- name: kubecf-github-release
run:
  path: kubecf/.concourse/tasks/upgrade.sh
