dependencies:
- name: eirini
  version: 1.0.1
  repository: http://opensource.suse.com/eirini-release/
  condition: features.eirini.enabled
- name: bits
  version: 1.0.14
  repository: http://opensource.suse.com/bits-service-release/
  condition: features.eirini.enabled
