# Disable tuning /proc/sys kernel parameters as locket is running on containers.
- type: replace
  path: /instance_groups/name=locket/jobs/name=locket/properties/set_kernel_parameters?
  value: false

- type: replace
  path: /instance_groups/name=locket/jobs/-
  value:
    name: cfdot
    release: diego
    properties:
      tls:
        ca_certificate: "((diego_rep_client.ca))"
        certificate: "((diego_rep_client.certificate))"
        private_key: "((diego_rep_client.private_key))"

# Add quarks properties for locket.
- type: replace
  path: /instance_groups/name=locket/jobs/name=locket/properties/quarks?
  value:
    ports:
    - name: locket
      protocol: TCP
      internal: 8891
    run:
      healthcheck:
        locket:
          readiness:
            exec:
              command:
              - /var/vcap/packages/cfdot/bin/cfdot
              - locks
              - --locketAPILocation=127.0.0.1:8891
              - --caCertFile=/var/vcap/jobs/cfdot/config/certs/cfdot/ca.crt
              - --clientCertFile=/var/vcap/jobs/cfdot/config/certs/cfdot/client.crt
              - --clientKeyFile=/var/vcap/jobs/cfdot/config/certs/cfdot/client.key
