{{- $_ := include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "bits"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "bits"
  template:
    metadata:
      labels:
        name: "bits"
    spec:
      dnsPolicy: "ClusterFirst"
      volumes:
        - name: bits-config
          secret:
            secretName: "bits"
            items:
            - key: bits-config-key
              path: bits-service.yml
        - name: bits-cert
          secret:
            secretName: {{ .Values.bits.tls_secret_name }}
      containers:
      - name: bits
        image: {{ .Values.bits.global.images.bits_service }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
        {{- if and (.Values.bits.blobstore.secret.name) (.Values.bits.blobstore.secret.passwordPath) }}
        env:
        - name: BITS_BLOBSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: "{{ .Values.bits.blobstore.secret.passwordPath }}"
              name: "{{ .Values.bits.blobstore.secret.name }}"
        {{- end }}
        volumeMounts:
        - name: bits-config
          mountPath: /workspace/jobs/bits-service/config
        - name: bits-cert
          mountPath: /workspace/jobs/bits-service/certs
        {{- with .Values.bits.resources }}
        {{- if or .cpu .memory }}
        resources:
          requests:
            {{- with .cpu }}
            cpu: {{ . }}
            {{ end }}
            {{- with .memory }}
            memory: {{ . }}
            {{- end }}
        {{- end }}
        {{- end }}

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: "bits"
  annotations:
spec:
  ports:
    - port: {{ if .Values.bits.ingress.use }}8888{{ else }}6666{{ end }}
      protocol: TCP
      targetPort: {{ if .Values.bits.ingress.use }}8888{{ else }}6666{{ end }}
      {{- with .Values.bits.services.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      name: bits
  selector:
    name: "bits"

  {{- if .Values.bits.services.nodePort }}
  type: "NodePort"
  {{- end }}

# Ingress
{{- if .Values.bits.ingress.use }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bits-registry
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.bits.ingress.annotations | indent 4 }}
spec:
  tls:
    - hosts:
      - "registry.{{ .Values.bits.ingress.endpoint }}"
      secretName: {{ .Values.bits.tls_secret_name }}
  rules:
    - host: "registry.{{ .Values.bits.ingress.endpoint }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: bits
              servicePort: 8888
{{- end }}
{{- end }}
