---
kind: pipeline
type: docker
name: default

trigger:
  ref:
  - refs/heads/test/**
  - refs/heads/master

workspace:
  base: /home/runner/builds
  path: kubecf

# Dockerfile source - https://github.com/f0rmiga/bazel-docker-image.
.anchors:
  bazel_image: &bazel_image thulioassis/bazel-docker-image:1.2.1

steps:
- name: lint:shellcheck
  image: *bazel_image
  commands:
  - ./dev/linters/shellcheck.sh
- name: lint:yamllint
  image: *bazel_image
  commands:
  - ./dev/linters/yamllint.sh
- name: lint:helmlint
  image: *bazel_image
  commands:
  - ./dev/linters/helmlint.sh
- name: build
  image: *bazel_image
  commands:
  - .drone/pipelines/default/steps/build/build.sh
- name: test
  image: *bazel_image
  volumes:
  - name: docker
    path: /var/lib/docker
  privileged: true
  commands:
  - ./.drone/pipelines/default/steps/test/test.sh

volumes:
- name: docker
  temp: {}
