# This ops file sets the openSUSE stemcells.

- type: replace
  path: /stemcells/alias=default
  value:
    alias: default
    os: {{ .Values.releases.defaults.stemcell.os | quote }}
    version: {{ .Values.releases.defaults.stemcell.version | quote }}

{{- $addons := list }}
{{- $addons = append $addons "forwarder_agent" }}
{{- $addons = append $addons "loggr-syslog-agent" }}
{{- $addons = append $addons "loggregator_agent" }}
{{- /*
These are disabled as we don't use use them yet, and don't have images
{{- $addons = append $addons "metrics-agent" }}
{{- $addons = append $addons "metrics-discovery-registrar" }}
*/}}
{{- $addons = append $addons "prom_scraper" }}

{{- range $addon := $addons }}
- type: replace
  path: /addons/name={{ $addon }}/include/stemcell/os=ubuntu-xenial/os
  value: {{ $.Values.releases.defaults.stemcell.os | quote }}
{{- end }}
