# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: minions-1-diego-cell-0
# spec:
#   clusterIP: None
#   type: ClusterIP
  
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: minions-1-diego-cell-0
# subsets:
# - addresses:
#   - ip: 172.22.216.231
