
{{- define "volumeMount" }}
- name: {{ .name}}-database-password
  mountPath: "/passwords/{{ .path }}"
  readOnly: true
{{- end }}

{{- if .Values.features.embedded_database.enabled -}}
{{- $databases := list (dict "name" "cloud-controller" "path" "cloud_controller" "secretName" "cc") }}
{{- $databases := append $databases (dict "name" "diego" "path" "diego" "secretName" "diego") }}
{{- $databases := append $databases (dict "name" "network-connectivity" "path" "network_connectivity" "secretName" "network-connectivity") }}
{{- $databases := append $databases (dict "name" "network-policy" "path" "network_policy" "secretName" "network-policy") }}
{{- $databases := append $databases (dict "name" "routing-api" "path" "routing-api" "secretName" "routing-api") }}
{{- $databases := append $databases (dict "name" "uaa" "path" "uaa" "secretName" "uaa") }}
{{- $databases := append $databases (dict "name" "locket" "path" "locket" "secretName" "locket") }}
{{- $databases := append $databases (dict "name" "credhub" "path" "credhub" "secretName" "credhub") }}

apiVersion: batch/v1
kind: Job
metadata:
  name: db-seeder
spec:
  template:
    spec:
      containers:
      - name: seeder
        image: {{ (index .Values "percona-xtradb-cluster").image.repository }}:{{ (index .Values "percona-xtradb-cluster").image.tag }}
        env:
        - name: DATABASE_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-pxc
              key: mysql-root-password
        - name: DATABASE_HOST
          value: {{ .Release.Name }}-pxc
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        volumeMounts:
        {{- range $database := $databases }}
        - name: {{ .name}}-database-password
          mountPath: "/passwords/{{ .path }}"
          readOnly: true
        {{- end }}
        command:
        - "/bin/bash"
        - "-c"
        - |-
          {{- .Files.Get "assets/scripts/jobs/pxc/seeder.sh" | nindent 10 }}

      volumes:
      {{- range $database := $databases }}
      - name: {{ .name }}-database-password
        secret:
          secretName: {{ $.Release.Namespace }}.var-{{ .secretName }}-database-password
      {{- end }}
      restartPolicy: Never

{{- end -}}
