---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-sizing
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
data:
  ops: |
    # adapter
{{- if .Values.sizing.adapter.instances }}
    - type: replace
      path: /instance_groups/name=adapter/instances
      value: {{.Values.sizing.adapter.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=adapter/instances
      value: 1
{{- end }}

    # api
{{- if .Values.sizing.api.instances }}
    - type: replace
      path: /instance_groups/name=api/instances
      value: {{.Values.sizing.api.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=api/instances
      value: 1
{{- end }}

{{- if .Values.features.eirini.enabled }}
    # bits
{{- if .Values.sizing.bits.instances }}
    - type: replace
      path: /instance_groups/name=bits/instances
      value: {{.Values.sizing.bits.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=bits/instances
      value: 1
{{- end }}

    # eirini
{{- if .Values.sizing.eirini.instances }}
    - type: replace
      path: /instance_groups/name=eirini/instances
      value: {{.Values.sizing.eirini.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=eirini/instances
      value: 1
{{- end }}
{{- end }}

    # cc-worker
{{- if .Values.sizing.cc_worker.instances }}
    - type: replace
      path: /instance_groups/name=cc-worker/instances
      value: {{.Values.sizing.cc_worker.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=cc-worker/instances
      value: 1
{{- end }}

    # database
{{- if .Values.sizing.database.instances }}
    - type: replace
      path: /instance_groups/name=database/instances
      value: {{.Values.sizing.database.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=database/instances
      value: 1
{{- end }}

    # diego-api
{{- if .Values.sizing.diego_api.instances }}
    - type: replace
      path: /instance_groups/name=diego-api/instances
      value: {{.Values.sizing.diego_api.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=diego-api/instances
      value: 1
{{- end }}

{{- if not .Values.features.eirini.enabled -}}
    # diego-cell
{{- if .Values.sizing.diego_cell.instances }}
    - type: replace
      path: /instance_groups/name=diego-cell/instances
      value: {{.Values.sizing.diego_cell.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=diego-cell/instances
      value: 1
{{- end }}
{{- end }}

    # doppler
{{- if .Values.sizing.doppler.instances }}
    - type: replace
      path: /instance_groups/name=doppler/instances
      value: {{.Values.sizing.doppler.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=doppler/instances
      value: 1
{{- end }}

    # log-api
{{- if .Values.sizing.log_api.instances }}
    - type: replace
      path: /instance_groups/name=log-api/instances
      value: {{.Values.sizing.log_api.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=log-api/instances
      value: 1
{{- end }}

    # nats
{{- if .Values.sizing.nats.instances }}
    - type: replace
      path: /instance_groups/name=nats/instances
      value: {{.Values.sizing.nats.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=nats/instances
      value: 1
{{- end }}

    # router
{{- if .Values.sizing.router.instances }}
    - type: replace
      path: /instance_groups/name=router/instances
      value: {{.Values.sizing.router.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=router/instances
      value: 1
{{- end }}

    # scheduler
{{- if .Values.sizing.scheduler.instances }}
    - type: replace
      path: /instance_groups/name=scheduler/instances
      value: {{.Values.sizing.scheduler.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=scheduler/instances
      value: 1
{{- end }}

    # singleton-blobstore
{{- if .Values.features.blobstore }}
{{- if eq .Values.features.blobstore.provider "singleton" }}
{{- if .Values.sizing.singleton_blobstore.instances }}
    - type: replace
      path: /instance_groups/name=singleton-blobstore/instances
      value: {{.Values.sizing.singleton_blobstore.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=singleton-blobstore/instances
      value: 1
{{- end }}
{{- end }}
{{- end }}

    # uaa
{{- if .Values.sizing.uaa.instances }}
    - type: replace
      path: /instance_groups/name=uaa/instances
      value: {{.Values.sizing.uaa.instances}}
{{- else if not .Values.high_availability }}
    - type: replace
      path: /instance_groups/name=uaa/instances
      value: 1
{{- end }}