{{- if .Values.testing.cf_acceptance_tests.enabled -}}

- path: /instance_groups/-
  type: replace
  value:
    azs:
    - z1
    instances: 1
    jobs:
    - name: acceptance-tests
      properties:
        acceptance_tests:
          admin_password: ((cf_admin_password))
          admin_user: admin
          api: api.((system_domain))
          apps_domain: ((system_domain))
          credhub_client: credhub_admin_client
          credhub_mode: assisted
          credhub_secret: ((credhub_admin_client_secret))
          include: '+tcp_routing'
          skip_ssl_validation: true
        bpm:
          enabled: true
      release: cf-acceptance-tests
    lifecycle: errand
    name: acceptance-tests
    networks:
    - name: default
    stemcell: default
    update:
      serial: true
    vm_type: minimal

{{- if .Values.features.credhub.enabled -}}

- path: /instance_groups/name=acceptance-tests/jobs/name=acceptance-tests/properties/acceptance_tests/credhub_client?
  type: replace
  value: credhub_admin_client
- path: /instance_groups/name=acceptance-tests/jobs/name=acceptance-tests/properties/acceptance_tests/credhub_mode?
  type: replace
  value: assisted
- path: /instance_groups/name=acceptance-tests/jobs/name=acceptance-tests/properties/acceptance_tests/credhub_secret?
  type: replace
  value: ((credhub_admin_client_secret))
- path: /instance_groups/name=acceptance-tests/jobs/name=acceptance-tests/properties/acceptance_tests/include?
  type: replace
  value: '+credhub,+tcp_routing'

{{- end }}

{{- end }}