# Add quarks properties for doppler.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=doppler/properties/quarks?
  value:
    ports:
    - name: doppler-grpc
      protocol: TCP
      internal: 8082
    run:
      healthcheck:
        doppler:
          readiness:
            exec:
              command: ["curl", "--fail", "--head", "--silent", "http://localhost:14825/health"]
