{{- if .Values.features.sle15_stack.enabled -}}
{{- $root := . -}}
- type: replace
  path: /releases/-
  value:
    name: sle15
    version: {{ (index .Values.releases "sle15").version | quote }}
    url: {{ include "kubecf.releaseURLLookup" (list .Values.releases "sle15") }}
    stemcell: {{ include "kubecf.stemcellLookup" (list .Values.releases "sle15") }}
{{- end }}
