bits:
  # set ingress endpoint when 'use_registry_ingress' is set to true
  ingress:
    use: false
    endpoint: ~
    annotations: {}

  blobstore:
    serviceName: "singleton-blobstore"
    userName: "blobstore-user"
    secret:
      name: "var-blobstore-admin-users-password"
      passwordPath: "password"

  global:
    images:
      bits_service: registry.suse.com/cap-staging/bits-service:bits-1.0.20-15.1.6.2.264-24.33

  # resources:
  #   cpu: 800m
  #   memory: 150Mi

  services:
    nodePort: 31666

  secrets:
    BITS_SERVICE_SECRET: secret
    BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
    BLOBSTORE_PASSWORD:  blobstore
    BITS_TLS_CRT: ~
    BITS_TLS_KEY: ~

  env:
    # Base domain of the SCF cluster.
    # Example: "my-scf-cluster.com"
    DOMAIN: 127.0.0.1.nip.io

  useExistingSecret: true
  tls_secret_name: bits-service-ssl
  tls_cert_name: certificate
  tls_key_name: private_key
  tls_ca_name: ca
